### ISSUE TITLE
Psetv2: `Output` message should have a blinder index field

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/ocean#21]
https://github.com/vulpemventures/ocean/blob/master/api-spec/protobuf/ocean/v1/types.proto#L42

**Comment by tiero** [comment]
also, address should be split in script & blind pub key, so we can pass op_return and future segwit versions

**Comment by louisinger** [comment]
> also, address should be split in script & blind pub key, so we can pass op_return and future segwit versions

address is OK for segwit version, script and blind pubkey and easier to read in my opinion. I prefer an optional parameter "script" in order to handle OP_RETURN (or whatever not encodable via address)

**Comment by tiero** [comment]
> > also, address should be split in script & blind pub key, so we can pass op_return and future segwit versions
> 
> address is OK for segwit version, script and blind pubkey and easier to read in my opinion. I prefer an optional parameter "script" in order to handle OP_RETURN (or whatever not encodable via address)

yes having addres AND script is fine, but you need also blinding pub key, in case of confidential OP_RETURN

**Comment by altafan** [comment]
Closed by #23
