### ISSUE TITLE
[WalletService] Blinding seed 

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/ocean#6]
The blinding seed is a concept unknown in GDK (it uses the same seed for both sign keys and blind keys - via SLIP77). is it something specific to tdex-daemon ?

Moreover, I'm not sure it's recommended to use different seeds for blinding and signing. Do u know a case where blinding seed **should be** different than signing seed ? cc @tiero @sekulicd

**Comment by tiero** [comment]
I think this comes from the multisig concept. But since we iterate on this and we use xor, would not be needed anymore.

So yes, better to remove blinding seed and ALWAYS use slip77 to derive for single sig HD wallets
