### ISSUE TITLE
[WalletService] CreateWallet and RestoreWallet seems to be duplicate

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/ocean#7]
Not sure to understand the difference between RestoreWallet and CreateWallet. IMO, we should restore in all cases even if it's the first time the user creates the wallet (via `CreateWallet`) because he could for instance reuse an old seed. In that case, we MUST detect transactions and addresses already used.

**Comment by tiero** [comment]
Agreed, maybe InitWallet is better?

**Comment by louisinger** [comment]
Or nothing ? I mean, wallet config is really something we need to expose via a service ? In my mind, the user who owns the wallet will run the ocean instance. At startup time, the ocean "server" could request the seed for instance.

**Comment by tiero** [comment]
GDK has a "login" method, we in the tdex daemon (and LND for example) we have `InitWallet` 

We can request a seed automatically, but how it works when you want to restore? Messing up manually with the file storage? I think an RPC for this makes sense

**Comment by sekulicd** [comment]
From my POV it is ok to have both methods RestoreWallet and CreateWallet.
With this we let one method do one thing and not having "one do it all", i think this way is cleaner for dev side but also for the wallet user when reading the doc.

**Comment by louisinger** [comment]
> From my POV it is ok to have both methods RestoreWallet and CreateWallet. With this we let one method do one thing and not having "one do it all", i think this way is cleaner for dev side but also for the wallet user when reading the doc.

@sekulicd my main problem is the GDK implementation. "restoring" concept does not exist in Green (for them create == restore). Thus, we can't tell to GDK to "do not restore". In conclusion, it's ok to have two RPCs but in some cases (including GDK wallets) create and restore will do the same thing. Which could also disturb the user.

**Comment by tiero** [comment]
Is it CreateWallet redundant with GenSeed + RestoreWallet ?

**Comment by louisinger** [comment]
> Is it CreateWallet redundant with GenSeed + RestoreWallet ?

using GDK ? yes

**Comment by altafan** [comment]
This is not strictly related to the topic, but I want at least to point out that with this design of the RPCs it's not possible at all to restore wallets with accounts using custom template scripts, regardless having a single InitWallet or 2 distinct rpc.

We may need to iterate over the protos once more to make it possible for such "custom" wallets to support the restore flow.
