### ISSUE TITLE
Docker: support named voulumes creating the data directory 

### ISSUE THREAD

**Issue by tiero** [vulpemventures/ocean#84]
Now we do expect operators to create the folder BEFORE running the service,  give very high permission to everyone (chmod 777) and attach the volume to run the container.

If we have the oceand binary to create the folder and assign permission, we then have the binary to create file he can read and write without any additional user intervention

**Comment by altafan** [comment]
Closed by dd0b884bcfa26defd84d5c2b1d7c254156d60d5b and ea1aaedba36f9272f13cffab5c60b9484eaf3db2
